name: Commit message check

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    uses: ./.github/workflows/commit-msg-check.yml
    with:
      check-stamp: false
      check-conventional: true
